In [1]:
import numpy as np

Напишите программу, которая:
- Запрашивает у пользователя ввод одномерного массива, элементы которого вводятся в виде чисел, разделенных пробелами.
- Преобразует введенную строку в массив NumPy.
- Запрашивает у пользователя индекс элемента, который необходимо извлечь из массива.
- Выводит значение элемента по запрошенному индексу.
- Запрашивает у пользователя ввод диапазона индексов в формате `начало:конец`, чтобы извлечь срез массива.
- Выводит срез массива.


In [2]:
input_array = input("Enter a one-dimensional array of numbers, separated by spaces: ")

array = np.array(list(map(float, input_array.split())))

index = int(input("Enter the index of the element to extract: "))

if 0 <= index < len(array):
    print("Element at index", index, ":", array[index])
else:
    print("Invalid index!")

slice_range = input("Enter the index range in the format 'start:end' to extract a slice: ")

try:
    start, end = map(int, slice_range.split(':'))
    print("Array slice:", array[start:end])
except ValueError:
    print("Invalid range format!")


Enter a one-dimensional array of numbers, separated by spaces:  1 2 3 
Enter the index of the element to extract:  4


Invalid index!


Enter the index range in the format 'start:end' to extract a slice:  1Ж"


Invalid range format!


Напишите программу, которая:
- Запрашивает у пользователя размеры матрицы MxN.
- Генерирует две матрицы указанных размеров, заполненные случайными числами от 0 до 9.
- Выводит обе сгенерированные матрицы на экран.
- Выполняет и выводит результат одной из следующих операций (на выбор пользователя): сложение матриц, умножение матриц, транспонирование одной из матриц.
- Если выбрано умножение, убедитесь, что размеры матриц соответствуют правилам матричного умножения.



In [4]:
import numpy as np

M = int(input("Enter the number of rows (M): "))
N = int(input("Enter the number of columns (N): "))

matrix1 = np.random.randint(0, 10, size=(M, N))
matrix2 = np.random.randint(0, 10, size=(M, N))

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

operation = input("Choose an operation - 'add' for addition, 'multiply' for multiplication, 'transpose' for transposition: ").lower()

if operation == 'add':
    result = matrix1 + matrix2
    print("Result of addition:\n", result)
elif operation == 'multiply':
    if matrix1.shape[1] == matrix2.shape[0]:
        result = matrix1 @ matrix2
        print("Result of multiplication:\n", result)
    else:
        print("Matrix dimensions do not allow multiplication!")
elif operation == 'transpose':
    matrix_choice = input("Transpose '1' for matrix1 or '2' for matrix2: ")
    if matrix_choice == '1':
        result = np.transpose(matrix1)
        print("Transposed Matrix 1:\n", result)
    elif matrix_choice == '2':
        result = np.transpose(matrix2)
        print("Transposed Matrix 2:\n", result)
else:
    print("Invalid operation choice!")


Enter the number of rows (M):  2
Enter the number of columns (N):  2


Matrix 1:
 [[5 2]
 [6 8]]
Matrix 2:
 [[6 4]
 [0 3]]


Choose an operation - 'add' for addition, 'multiply' for multiplication, 'transpose' for transposition:  multiply


Result of multiplication:
 [[30 26]
 [36 48]]
