Сравнение производительности операций над массивами:

Напишите программу, которая:
- Генерирует два больших одномерных массива с 1 миллионом элементов каждый, заполненных случайными числами.
- Сначала выполняет поэлементное сложение этих массивов, используя циклы Python.
- Затем выполняет ту же операцию, используя возможности NumPy.
- Измеряет и выводит время выполнения каждого подхода.


In [2]:
import numpy as np
import random

In [10]:
size = 10**6
array1 = np.array([random.random() for _ in range(size)])
array2 = np.array([random.random() for _ in range(size)])

In [11]:
%%timeit

[array1[i] + array2[i] for i in range(size)]

289 ms ± 23.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%%timeit
array1+array2

1.71 ms ± 129 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Анализ расположения данных в памяти:
Создать большой двумерный массив и исследовать, как изменение порядка (C-style и Fortran-style) влияет на производительность операций сложения и умножения.
Можно использовать тот же бенчмарк что и в лекции. Необходимо погуглить про то, как завести массив с порядком в Fortran-style. Не забывайте про magic в jupyter.


In [13]:
array_c = np.random.rand(5000, 5000)
array_f = np.array(array_c, order='F')

In [14]:
%%timeit
array_c + array_c

48.1 ms ± 842 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
%%timeit 
array_f+array_f

49.2 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%%timeit
array_c @ array_c

1.18 s ± 88.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%%timeit
array_f @ array_f

1.39 s ± 204 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Обратная матрица и определитель:

Напишите программу, которая:
- Запрашивает у пользователя размер квадратной матрицы N.
- Генерирует квадратную матрицу размером N x N, заполненную случайными числами от -10 до 10.
- Выводит сгенерированную матрицу на экран.
- Вычисляет и выводит определитель матрицы.
- Если определитель не равен нулю, программа должна вычислить и вывести обратную матрицу. В противном случае, программа должна сообщить, что обратной матрицы не существует.


In [24]:
N = int(input("Введите размерность квадратной матрицы: "))
m = np.random.randint(-10,10,size=(N,N))
print(m)
det = np.linalg.det(m)
print('Детерминант мартицы: ', np.round(det,2))
if det!=0:
    print('Обратная матрица:')
    print(np.round(np.linalg.inv(m)),2)
else:
    print('Обратной матрицы не существует')

Введите размерность квадратной матрицы:  3


[[ 7 -6  7]
 [-7  5 -5]
 [ 3 -9 -5]]
Детерминант мартицы:  146.0
Обратная матрица:
[[-0. -1. -0.]
 [-0. -0. -0.]
 [ 0.  0. -0.]] 2
