Введение в NumPy и массивы
===
1) Что такое NumPy и зачем он нужен?
----
NumPy - это фундаментальная библиотека для научных вычислений в Python. Она предоставляет поддержку для больших, многомерных массивов и матриц, включая широкий набор математических функций для операций с этими массивами.


In [1]:
import numpy as np


2) Создание массивов:
----
Массивы NumPy эффективнее списков Python по нескольким причинам. Они занимают меньше памяти, предоставляют быстродействие операций и имеют удобный синтаксис. 



In [2]:
# Одномерный массив
one_d_array = np.array([1, 2, 3])
print(one_d_array)

# Двумерный массив
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(two_d_array)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [3]:
list_2d = [[1, 2], [3, 4]]
two_d_array = np.array(list_2d)


Есть еще популярный термин – вектор-столбец. Это 2-мерный массив, в котором всего один столбец. Например,


In [4]:
col = np.array([[10], [20]])
print(col)
# [[10]
#  [20]]


[[10]
 [20]]


Можно создавать массивы с помощью специальных функций. Из документации:


In [5]:
ones_array = np.ones((3, 4))
print(ones_array)



zeros_array = np.zeros_like(ones_array)
print(zeros_array)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


arange
--
Функция arange подобна range. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг — целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.


In [6]:
a = np.arange(0, 9, 2)
print(a)
b = np.arange(0., 8, 2)
print(b)


[0 2 4 6 8]
[0. 2. 4. 6.]


linspace
--
Последовательности чисел с постоянным шагом можно также создавать функцией linspace. Начало и конец диапазона включаются; последний аргумент — число точек.

In [7]:
a = np.linspace(0, 8, 7)
print(a)


[0.         1.33333333 2.66666667 4.         5.33333333 6.66666667
 8.        ]


*Упражнение: создайте и выведите последовательность чисел от 10 до 20 с постоянным шагом, длина последовательности – 21. Скажите сначала устно, какой должен быть ответ.*


In [8]:
np.linspace(10,20,21)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

3) Работа с размерностями:
---
Размерности в NumPy определяют, сколько индексов требуется для адресации элемента. Одномерные массивы – векторы, двумерные – матрицы (таблицы). Для того чтобы посмотреть размерность, нужно обратиться к полю ndim.


In [9]:
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array.ndim


3

In [10]:
three_d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_d_array.shape


(2, 2, 2)

In [11]:
three_d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Задание для закрепления.
--
1. Сколько строк и столбцов будет у матрицы, которая будет выведена следующим кодом?


In [12]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2. Что выведет следующий код?


In [13]:
print(array.shape)
print(len(array))


(4, 3)
4


4) Типы элементов в массивах
---
В numpy обычно в рамках одного массива все элементы имеют один и тот же тип данных! Но это не ограничение на уровне предупреждения, можно использовать и разные типы (но они будут конвертироваться к одному).


In [14]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
two_d_array


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
two_d_array = np.array([[1, 2, 3.0], [4, 5, 6]])
two_d_array


array([[1., 2., 3.],
       [4., 5., 6.]])

In [16]:
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"]])
two_d_array


array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [17]:
two_d_array = np.array([[1, 2, 3], ["A", "B", "C"*28]])
two_d_array


array([['1', '2', '3'],
       ['A', 'B', 'CCCCCCCCCCCCCCCCCCCCCCCCCCCC']], dtype='<U28')

А тут 28. Уже похоже, что что-то происходит неоптимально.

Сколько байт в памяти это будет занимать? В этом поможет поле itemsize


In [18]:
x=np.array([1, 2, 3])
x.dtype

dtype('int64')

In [19]:
print(np.array([1, 2, 3]).itemsize)


8


In [20]:
print(np.array([[1, 2, 3], ["A", "B", "C"]]).itemsize)

84


Что будет, если попробовать записать в такой массив строку большей длины, например?


In [21]:
a = np.array([[1, 2, 3], ["A", "B", "C"]],
            dtype='<U11')
a


array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U11')

In [22]:
a[0][0] = "a"*10+"b"*10
a

array([['aaaaaaaaaab', '2', '3'],
       ['A', 'B', 'C']], dtype='<U11')

список


In [23]:
list_int_str = [[1, 2, 3], ["A", "B", "C"]]
print(list_int_str)
list_int_float = [[1, 2, 3.0], [4, 5, 6]]
print(list_int_float)


[[1, 2, 3], ['A', 'B', 'C']]
[[1, 2, 3.0], [4, 5, 6]]


Задачи
--

In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[1] + arr[3])


6


In [25]:
arr = np.array([1.0, 2, 3])
print(arr.dtype)

arr = np.arange(5, 15, 2)
print(arr)


float64
[ 5  7  9 11 13]


2. Создание и изучение массивов:
 --
Создайте одномерный массив из случайных чисел. Выведите его тип, размер и содержимое.


In [26]:
import numpy as np
import random

# Задаем длину массива
length = 10

# Создаем массив случайных чисел от 0 до 100
random_array = np.array([random.randint(0, 100) for _ in range(length)])

# Выводим тип, размер и содержимое массива
print("Тип массива:", random_array.dtype)
print("Размер массива:", random_array.size)
print("Содержимое массива:", random_array)


Тип массива: int64
Размер массива: 10
Содержимое массива: [27 17 29  1 77 34 39 46 32 70]


Создайте массив размером 3x4, полностью заполненный единицами, и выведите его.


In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Используя функцию np.arange, создайте массив чисел от 0 до 10 с шагом 2. Затем создайте массив с теми же числами, используя np.linspace, и сравните результаты.

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
x.astype('str')

array(['1', '2', '3'], dtype='<U21')

In [35]:
two_d_list = [[1, 2, 3], [4, 5, 6]]
# Сложение массивов
print(two_d_list + two_d_list)
# [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
# Умножение массива на число
print(two_d_list * 2)
# [[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [36]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
# Сложение массивов
print(two_d_array + two_d_array)
# [[ 2  4  6]
#  [ 8 10 12]]
# Умножение массивов
print(two_d_array * two_d_array)
# [[ 1  4  9]
#  [16 25 36]]
# Умножение массива на число – каждое число в массиве умножится на это число
print(two_d_array * 5)
# [[ 5 10 15]
#  [20 25 30]]


[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[ 5 10 15]
 [20 25 30]]


In [37]:
square = np.array([[1, 2], [4, 5]])
two_d_array + square


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [38]:
one_d_array = np.array([10, 20, 30])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(one_d_array + two_d_array)


[[11 22 33]
 [14 25 36]]


In [39]:
col = np.array([1, 2])

In [40]:
two_d_array = np.array([3, 4, 5])
print(np.concatenate( [col, two_d_array] ))


[1 2 3 4 5]


In [41]:
col = np.array([[10], [20], [30]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col + two_d_array)


ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [42]:
mult = np.array([[10, 20, 30]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(mult * two_d_array)


[[ 10  40  90]
 [ 40 100 180]]


In [43]:
a = np.array([0, 2, 1])
b = np.array([3, 4, 5])
print(a - b)  # [-3 -2 -4]
print(a / b)  # [0.  0.5 0.2]
print(a ** 2)  # [0 4 1]


[-3 -2 -4]
[0.  0.5 0.2]
[0 4 1]


In [44]:
print(b / a)  

[inf  2.  5.]


/var/folders/2w/zv9tyjqd4n1cxm711skjgh9c0000gn/T/ipykernel_11229/2917386247.py:1: RuntimeWarning: divide by zero encountered in divide
  print(b / a)


In [45]:
print(type((b / 0)[0]))


<class 'numpy.float64'>


/var/folders/2w/zv9tyjqd4n1cxm711skjgh9c0000gn/T/ipykernel_11229/73444277.py:1: RuntimeWarning: divide by zero encountered in divide
  print(type((b / 0)[0]))


In [46]:
two_d_array = np.array([[1,2,3], [4,5,6]])
print(two_d_array+1)

[[2 3 4]
 [5 6 7]]


In [47]:
col = np.array([[10], [20], [30]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(col + two_d_array)


ValueError: operands could not be broadcast together with shapes (3,1) (2,3) 

In [48]:
mult = np.array([[10, 20, 30]])
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])
print(mult * two_d_array)


[[ 10  40  90]
 [ 40 100 180]]


In [49]:
np.sin(4)

-0.7568024953079282

In [50]:
cube = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(cube * cube)
print(cube + np.array([[10, 20], [30, 40]]))
print(cube + np.array([[10, 20]]))


[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]
[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]
[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [51]:
print(cube + np.array([[10, 20], [30, 40]]))

[[[11 22]
  [33 44]]

 [[15 26]
  [37 48]]]


In [52]:
cube

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
print(cube + np.array([[10, 20]]))

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [54]:
print(cube + np.array([[10], [20]]))

[[[11 12]
  [23 24]]

 [[15 16]
  [27 28]]]


In [55]:
print(cube + np.array([[10], [20]]))

[[[11 12]
  [23 24]]

 [[15 16]
  [27 28]]]


In [56]:
print(cube + np.array([10, 20]))


[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


In [57]:
np.linspace(0,15,16)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [65]:
d=np.array([[ 0 , 1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15]])

In [66]:
d.shape

(4, 4)

In [67]:
d*np.array([ 8,  9, 10, 11])

array([[  0,   9,  20,  33],
       [ 32,  45,  60,  77],
       [ 64,  81, 100, 121],
       [ 96, 117, 140, 165]])

In [68]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))


[  0.  nan  inf -inf]


/var/folders/2w/zv9tyjqd4n1cxm711skjgh9c0000gn/T/ipykernel_11229/2320364298.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))
/var/folders/2w/zv9tyjqd4n1cxm711skjgh9c0000gn/T/ipykernel_11229/2320364298.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))


In [70]:
np.all([False,2,3])

False

In [73]:
d = np.linspace(0,15,16).reshape(4,4)

In [74]:
d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [76]:
d[2:3][0]

array([ 8.,  9., 10., 11.])

In [77]:
array[:,2]

array([ 3,  6,  9, 12])

In [78]:
d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])