Элементы матричной алгебры. Обратные матрицы и определитель
==
1) **Векторы и операции над ними в практических задачах**

Векторы (или одномерные массивы) в практических задачах возникают всякий раз, когда мы имеем дело с упорядоченным набором чисел.
Например, если мы решили записать ежедневные расходы в течение недели или среднюю температуру воздуха по месяцам года:


In [2]:
import numpy as np

In [3]:
# Вектор ежедневных расходов (в евро)
daily_expenses = np.array([10, 20, 15, 10, 30, 50, 50])

# Температура воздуха по месяцам (в градусах Цельсия)
temperature = np.array([1, 2, 6, 11, 16, 19, 21, 21, 16, 11, 6, 2])


Операции над векторами – это операции преобразования компонентов этих векторов. Например, если нужно изменить единицы измерения:


In [4]:
# Перевод ежедневных расходов в доллары
print(daily_expenses * 1.1)
# [11.  22.  16.5 11.  33.  55.  55. ]

# Перевод температуры в Фаренгейты
print(1.8 * temperature + 32)
# [33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]


[11.  22.  16.5 11.  33.  55.  55. ]
[33.8 35.6 42.8 51.8 60.8 66.2 69.8 69.8 60.8 51.8 42.8 35.6]


Примеры



In [5]:
print(daily_expenses.sum())

print(temperature.mean())

print(daily_expenses.max())

print(temperature[5:8])

185
11.0
50
[19 21 21]


Также в практических задачах используются и поэлементные операции с несколькими векторами:


In [7]:
# Доходы мужа по месяцам (в евро)
income_m = np.array([2000, 3000, 3500, 3000, 3000, 2500, 3500, 2000, 2500, 3000, 3500, 4000])

# Доходы жены по месяцам (в евро)
income_f = np.array([1500, 2500, 6000, 1100, 1600, 1900, 2100, 4200, 6000, 1100, 6000, 2000])

# Курс евро к доллару по месяцам
eur2usd = np.array([1.0779, 1.0716, 1.071, 1.096, 1.0879, 1.0834, 1.1056, 1.0916, 1.0686, 1.0561, 1.0804, 1.0902])

# Семейный доход в евро
income = income_m + income_f
print(income)
# [3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]

# Семейный доход в долларах
income_usd = income * eur2usd
print(income_usd)
# [ 3772.65  5893.8  10174.5   4493.6   5004.34  4766.96  6191.36  6767.92
#   9083.1   4330.01 10263.8   6541.2 ]


[3500 5500 9500 4100 4600 4400 5600 6200 8500 4100 9500 6000]
[ 3772.65  5893.8  10174.5   4493.6   5004.34  4766.96  6191.36  6767.92
  9083.1   4330.01 10263.8   6541.2 ]


2) **Матрицы в практических задачах**

Матрицы (или двумерные массивы) в практических задачах возникают всякий раз, когда нам нужно работать с несколькими родственными упорядоченными наборами чисел.
Например, доходы мужа и жены из предыдущего примера можно объединить в одну матрицу:


In [10]:
# Доходы членов семьи по месяцам 
income_matrix = np.vstack([income_m, income_f])

print(income_matrix)

# [[2000 3000 3500 3000 3000 2500 3500 2000 2500 3000 3500 4000]
#  [1500 2500 6000 1100 1600 1900 2100 4200 6000 1100 6000 2000]]


[[2000 3000 3500 3000 3000 2500 3500 2000 2500 3000 3500 4000]
 [1500 2500 6000 1100 1600 1900 2100 4200 6000 1100 6000 2000]]


Рассмотрим еще один пример. Кондитерская производит несколько видов десертов. Для каждого необходимы мука, яйца и сахар, но в разном количестве. Необходимое количество опишем матрицей, в которой каждая строка описывает одну партию какого-то десерта, при этом первый столбец показывает количество муки в килограммах, второй столбец – количество яиц в штуках, третий – количество сахара в килограммах.


In [11]:
# Расход продуктов  
goods = np.array([[0.5, 6, 0.1],
                  [1, 10, 0.5],
                  [0.3, 10, 0.6],
                  [0.5, 7, 0.3]])

print(goods)


[[ 0.5  6.   0.1]
 [ 1.  10.   0.5]
 [ 0.3 10.   0.6]
 [ 0.5  7.   0.3]]


Пусть у нас также известна стоимость килограмма муки, одного яйца и килограмма сахара. 


In [12]:
prices = np.array([0.75, 0.22, 0.88])

print(goods * prices)



[[0.375 1.32  0.088]
 [0.75  2.2   0.44 ]
 [0.225 2.2   0.528]
 [0.375 1.54  0.264]]


Теперь мы знаем, сколько стоит каждый продукт, необходимый для каждого десерта. Впрочем, на практике нас обычно интересуют суммарные затраты, а их мы можем получить с помощью матричного произведения, однако вектор стоимости продуктов придется преобразовать в столбец.

In [13]:
prices_col = prices.reshape(3,1)
expenses = goods @ prices_col
print(expenses)
print(expenses.sum())


[[1.783]
 [3.39 ]
 [2.953]
 [2.179]]
10.305000000000001


Итак, теперь мы знаем затраты на выпечку каждой партии каждого десерта, а также суммарные затраты, если у каждого десерта выпускается только одна партия.

Задание для закрепления. Фирма закупает ноутбуки и стационарные компьютеры для оборудования офисов на двух этажах здания. На первом этаже планируется поставить 20 стационарных компьютеров и 20 ноутбуков. На втором этаже – 12 стационарных компьютеров и 35 ноутбуков. Компьютер стоит 850 евро, ноутбук – 1125 евро. Запишите матрицу А, описывающую количество компьютеров и ноутбуков на каждом этаже. Запишите вектор-столбец с ценами компьютеров и ноутбуков. С помощью матричных операций вычислите стоимость оборудования на каждом этаже.


Решение:



In [14]:
# Количество оборудования  
equipment = np.array([[20, 20], [12, 35]])
# Цены
prices = np.array([[850], [1125]])

print(equipment @ prices)


[[39500]
 [49575]]


3) **Системы уравнений и обратная матрица**


In [16]:
equipment = np.array([[20, 20], [12, 35]])

inverse = np.linalg.inv(equipment) # обратная матрица

print(inverse)

print(inverse @ equipment)

print(equipment @ inverse)


[[ 0.07608696 -0.04347826]
 [-0.02608696  0.04347826]]
[[ 1.00000000e+00  1.38777878e-16]
 [-1.11022302e-16  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00]]


In [17]:
equipment = np.array([[20, 20], [12, 35]])

expenses = np.array([[40000], [50000]])

inverse = np.linalg.inv(equipment)

print(inverse @ expenses)


[[ 869.56521739]
 [1130.43478261]]


Задание для закрепления. 

Выполните проверку, что полученный вектор цен удовлетворяет матричному уравнению – подставьте значения в уравнения или выполните умножение матрицы на этот столбец.


Решение.



In [18]:
x = np.array([[ 869.56521739],  [1130.43478261]])
print(equipment @ x)


[[40000.        ]
 [50000.00000003]]


4) **Определитель**

Давайте в предыдущей задаче изменим количество оборудования на этажах: пусть теперь на втором этаже компьютеров и ноутбуков будет по 30.
Если мы попробуем найти обратную матрицу в этом случае, то получим ошибку:


In [20]:
equipment = np.array([[20, 20], [30, 30]])
#inverse = np.linalg.inv(equipment)
#print(inverse)


Обратная матрица существует не всегда, и если найти обратную матрицу невозможно, то numpy выбрасывает ошибку Singular matriх (если исходная матрица была квадратной). Если обратная матрица не существует, то любая система уравнений с исходной матрицей либо не имеет решений, либо имеет их бесконечное множество. Обычно нас будет интересовать случай, когда система имеет единственное решение. Для проверки единственности решения используют определитель матрицы.
Определитель – специальная числовая характеристика матрицы. Система уравнений с данной матрицей имеет единственное решение, только если ее определитель не равен нулю.


In [21]:
equipment = np.array([[20, 20], [30, 30]])
det = np.linalg.det(equipment)

print(det)


0.0


Задание для закрепления: 

Вычислите определитель предыдущей версии матрицы 

equipment = np.array([[20, 20], [12, 35]])


5) **Решение задач**

Матрица goods, как в примере выше, описывает количество муки, яиц и сахара в трех видах десертов некоторой кондитерской. Известно, что затраты на выпечку первого десерта составляют 2 евро, второго – 4 евро, третьего – 3 евро. Найдите, сколько должны стоить мука, яйца и сахар для такой себестоимости десертов.


In [23]:
# Расход продуктов  
goods = np.array([[0.5, 6, 0.1],
                  [1, 10, 0.5],
                  [0.3, 10, 0.6]])
np.linalg.det(goods)

-1.4999999999999998

In [24]:
expenses = np.array([[2,],[4],[4]])
res = np.linalg.inv(goods)@expenses
print(res)

[[0.26666667]
 [0.28      ]
 [1.86666667]]


Вопросы производительности. Работа со случайными числами
====
1) **Скорость NumPy**

NumPy эффективно использует память для хранения массивов. Операции выполняются на уровне C, что минимизирует накладные расходы интерпретатора Python.
Благодаря тому, что элементы массива хранятся в памяти последовательно и имеют фиксированный размер, NumPy может точно вычислить, где в памяти находится каждый элемент. 

Напишем код для перемножения элементов матрицы с самой собой. Сравним скорость работы и убедимся в том, что результат будет одинаковым.


In [31]:
N = 5000
list_2d = [[i + N*j for i in range(N)] for j in range(N)]
array_2d = np.array(list_2d)

In [32]:
%%timeit
list_2d_mult = [[list_2d[i][j] * list_2d[i][j] for j in range(N)] for i in range(N)]


2.32 s ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%%timeit
arr = []
for i in range(N):
    subarr = []
    for j in range(N):
        subarr.append(list_2d[i][j] * list_2d[i][j])
    arr.append(subarr)


2.84 s ± 428 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
%%timeit
array_2d_mult = array_2d * array_2d



74.2 ms ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


2) **Последовательное и строчное расположение:**

В NumPy можно выбирать между "C-style" и "Fortran-style" порядками хранения данных, где "C-style" означает последовательное расположение по последнему измерению (по строкам), а "Fortran-style" - по первому измерению (по столбцам).


In [35]:
array_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
array_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')

Разница:
* C-style (order='C'): данные в памяти хранятся так, что элементы одной строки находятся последовательно.
* Fortran-style (order='F'): данные в памяти хранятся так, что элементы одного столбца находятся последовательно.

3) **Работа с библиотекой numpy.random**

Создание массива случайных чисел из 5 элементов со значениями из интервала от 0 до 1:


In [36]:
print(np.random.rand(5))


[0.84857577 0.42876817 0.64818491 0.86111518 0.72041406]


Создание массива случайных целых чисел размером 5x5 в диапазоне от 10 (включительно) до 20 (включительно):


In [41]:
print(np.random.randint(10, 21, (5, 5)))


[[12 14 19 10 13]
 [12 18 10 17 10]
 [16 17 10 18 15]
 [13 12 18 17 19]
 [15 15 14 20 18]]


Напишите программу, которая:
- Запрашивает у пользователя количество точек данных N.
- Генерирует массив из N случайных точек (координаты x и y), используя нормальное распределение.
- Выводит на экран первые 10 сгенерированных точек (если N было больше 10).
- Вычисляет и выводит среднее значение и стандартное отклонение для координат x и y.


In [54]:
N = int(input("Enter number of poitns: "))
points = np.random.normal(size=(N, 2))
print(points[:10])
mean_x, mean_y = np.round(np.mean(points, axis=0),2)
std_x, std_y = np.round(np.std(points, axis=0),2)

print(f'Mean x: {mean_x}, mean y: {mean_y}')
print(f'Std x: {std_x}, std y: {std_y}')

Enter number of poitns:  10


[[-0.91600176 -1.40370302]
 [ 0.08084085  1.4519261 ]
 [ 0.12370581  0.28180797]
 [-1.06777475 -2.01037392]
 [-0.21032825 -0.45263197]
 [-1.73397467 -0.46741194]
 [-0.46016369  1.78966471]
 [-0.93653242 -0.48049175]
 [-0.36852815 -1.18904841]
 [-0.07120565 -0.60999653]]
Mean x: -0.56, mean y: -0.31
Std x: 0.56, std y: 1.14


array([[ 0.7867702 , -1.18240132],
       [ 0.81555476, -0.96021508],
       [ 0.00275437, -0.14243714],
       [-0.40251264,  0.60833345]])